apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-mqtt-exporter
  annotations:
    iot.metrics.io/service_should_be_scraped: "true"
    iot.metrics.io/scrape_port: "{{ .Values.mqttExporter.internalPort }}"
  labels:
    app.kubernetes.io/name: mqtt-exporter
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
    - name: mqtt-exporter-port
      port: {{ .Values.mqttExporter.internalPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: mqtt-exporter
    app.kubernetes.io/instance: {{ .Release.Name }}
